/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:da40caf4-6353-477d-8786-0eaff3506659",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_BJyGPnLps",
    "aws_user_pools_web_client_id": "3k6l8j90oestltchg4qihrull",
    "oauth": {}
};


export default awsmobile;
